// src/constants/applicantData.js

export const applicantData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@gmail.com",
    phone: "+91 9876543210",
    title: "Senior React Developer",
    experience: "5 Years",
    skills: [
      "React",
      "JavaScript",
      "Redux",
      "TypeScript",
      "HTML",
      "CSS",
    ],
    location: "Bangalore",
    appliedDate: "2026-06-28",
    status: "Applied",
    resume: "john-doe-resume.pdf",
    education: "B.Tech Computer Science",
    company: "Infosys",
    coverLetter:
      "I am excited to apply for the React Developer position.",
      resumeUrl:
      "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
  },
  {
    id: 2,
    firstName: "Sarah",
    lastName: "Wilson",
    email: "sarah.wilson@gmail.com",
    phone: "+91 9123456780",
    title: "Frontend Engineer",
    experience: "4 Years",
    skills: [
      "React",
      "Next.js",
      "JavaScript",
      "Tailwind CSS",
    ],
    location: "Hyderabad",
    appliedDate: "2026-06-27",
    status: "Screening",
    resume: "sarah-wilson-resume.pdf",
    education: "B.E Information Technology",
    company: "TCS",
    coverLetter:
      "Looking forward to contributing to your engineering team.",
  },
  {
    id: 3,
    firstName: "Amit",
    lastName: "Sharma",
    email: "amit.sharma@gmail.com",
    phone: "+91 9988776655",
    title: "React Developer",
    experience: "3 Years",
    skills: [
      "React",
      "Node.js",
      "MongoDB",
      "Express",
    ],
    location: "Pune",
    appliedDate: "2026-06-26",
    status: "Technical Round",
    resume: "amit-sharma-resume.pdf",
    education: "MCA",
    company: "Capgemini",
    coverLetter:
      "Passionate about building scalable React applications.",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    email: "priya.patel@gmail.com",
    phone: "+91 9012345678",
    title: "UI Developer",
    experience: "4 Years",
    skills: [
      "React",
      "Bootstrap",
      "CSS",
      "Figma",
    ],
    location: "Mumbai",
    appliedDate: "2026-06-25",
    status: "HR Round",
    resume: "priya-patel-resume.pdf",
    education: "B.Sc IT",
    company: "Accenture",
    coverLetter:
      "I enjoy creating accessible and responsive user interfaces.",
  },
  {
    id: 5,
    firstName: "Rahul",
    lastName: "Verma",
    email: "rahul.verma@gmail.com",
    phone: "+91 9876501234",
    title: "MERN Developer",
    experience: "6 Years",
    skills: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
    ],
    location: "Delhi",
    appliedDate: "2026-06-24",
    status: "Selected",
    resume: "rahul-verma-resume.pdf",
    education: "B.Tech",
    company: "Cognizant",
    coverLetter:
      "Excited to join your development team.",
  },
  {
    id: 6,
    firstName: "Neha",
    lastName: "Gupta",
    email: "neha.gupta@gmail.com",
    phone: "+91 9876123456",
    title: "Frontend Developer",
    experience: "2 Years",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
    ],
    location: "Chennai",
    appliedDate: "2026-06-23",
    status: "Rejected",
    resume: "neha-gupta-resume.pdf",
    education: "BCA",
    company: "HCL",
    coverLetter:
      "Thank you for considering my application.",
  },
  {
    id: 7,
    firstName: "Karan",
    lastName: "Singh",
    email: "karan.singh@gmail.com",
    phone: "+91 9090909090",
    title: "React Developer",
    experience: "4 Years",
    skills: [
      "React",
      "Redux",
      "REST API",
      "Git",
    ],
    location: "Noida",
    appliedDate: "2026-06-22",
    status: "Interview Scheduled",
    resume: "karan-singh-resume.pdf",
    education: "B.Tech",
    company: "Wipro",
    coverLetter:
      "I have hands-on experience building enterprise React applications.",
  },
  {
    id: 8,
    firstName: "Anjali",
    lastName: "Mehta",
    email: "anjali.mehta@gmail.com",
    phone: "+91 9345678912",
    title: "Frontend Engineer",
    experience: "5 Years",
    skills: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "Material UI",
    ],
    location: "Ahmedabad",
    appliedDate: "2026-06-21",
    status: "Withdrawn",
    resume: "anjali-mehta-resume.pdf",
    education: "B.E Computer Engineering",
    company: "IBM",
    coverLetter:
      "Thank you for the opportunity.",
  },
];